export const SUDOKU = {
  INIT_GAME: "INIT_GAME",
  SET_SIZE: "SET_SIZE",
  SET_DIFFICULTY: "SET_DIFFICULTY",
  CLEAR: "CLEAR_SUDOKU",
}

export const HETMANI = {
  INIT_GAME: "INIT_HETMANI_GAME",
  SET_SIZE: "SET_HETMANI_SIZE",
  CLEAR: "CLEAR_HEAMTNI",
}
